version: '3.7'

services:
  db:
    image: postgres:13.2
    volumes:
      - ./docker/db:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    expose:
      - 5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  alembic:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi-base:latest
    environment:
      SQL_DATABASE_URL: ${SQL_DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
    command: [ "alembic", "upgrade", "head" ]
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi-base:latest
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      SQL_DATABASE_URL: ${SQL_DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db
      - alembic